# NOTE: use 'sops updatekeys --yes secrets/infra.yaml' to add/remove recipients.
keys:
  - &jkachmar "0107655CC20AFD1A8F3F9872C1782440640BC696"
  - &chronos "age1v5unwn54mcxm2yd540wvdkqrm84a62yrj3tkq294whygpjl2gu6st83exg"
creation_rules:
  - path_regex: (hosts/chronos|overlays/plex-plexpass)/secrets.yaml$
    key_groups:
      - pgp:
          - *jkachmar
        age:
          - *chronos
  - path_regex: hosts/.*/secrets.yaml$
    key_groups:
      - pgp:
          - *jkachmar
        age:
